In [2]:
import pandas as pd
import matplotlib.pyplot as plt
d=pd.read_csv('/content/Real estate (1) (1).csv')
print(d)
x=d.iloc[:,0:1]
y=d.iloc[:,1:2]
print(x,y)
from sklearn.model_selection import train_test_split
X_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.10,random_state=5)
print(X_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
import numpy as np
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.linear_model import Lasso 
model_lasso= Lasso(alpha=0.01)
model_lasso.fit(x,y) 
pred_train_lasso= model_lasso.predict(x_test)
print(mean_squared_error(y_test,pred_train_lasso))
import numpy as np
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.linear_model import Lasso 
model_lasso= Lasso(alpha=0.01)
model_lasso.fit(x,y) 
pred_train_lasso= model_lasso.predict(x_test)
print(mean_squared_error(y_test,pred_train_lasso))

      No  X1 transaction date  X2 house age  \
0      1             2012.917          32.0
1      2             2012.917          19.5
2      3             2013.583          13.3
3      4             2013.500          13.3
4      5             2012.833           5.0
..   ...                  ...           ...
409  410             2013.000          13.7
410  411             2012.667           5.6
411  412             2013.250          18.8
412  413             2013.000           8.1
413  414             2013.500           6.5

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10
1                                 306.59470                                9
2                                 561.98450                                5
3                                 561.98450                                5
4                                 390.56840                                5
..                                      ...                              ...
409                              4082.01500                                0
410                                90.45606                                9
411                               390.96960                                7
412                               104.81010                                5
413                                90.45606                                9

     X5 latitude  X6 longitude  Y house price of unit area
0       24.98298     121.54024                        37.9
1       24.98034     121.53951                        42.2
2       24.98746     121.54391                        47.3
3       24.98746     121.54391                        54.8
4       24.97937     121.54245                        43.1
..           ...           ...                         ...
409     24.94155     121.50381                        15.4
410     24.97433     121.54310                        50.0
411     24.97923     121.53986                        40.6
412     24.96674     121.54067                        52.5
413     24.97433     121.54310                        63.9

[414 rows x 8 columns]
      No
0      1
1      2
2      3
3      4
4      5
..   ...
409  410
410  411
411  412
412  413
413  414

[414 rows x 1 columns]      X1 transaction date
0               2012.917
1               2012.917
2               2013.583
3               2013.500
4               2012.833
..                   ...
409             2013.000
410             2012.667
411             2013.250
412             2013.000
413             2013.500

[414 rows x 1 columns]
(372, 1)
(372, 1)
(42, 1)
(42, 1)
0.07154464517713029
0.07154464517713029

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('/content/Real estate (1) (1).csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values
print(X)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], 
remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
b1=1
b0=1
summation = 0 
n = len(y)
for i in range (0,n): 
    y_bar =(b1*y[i])+b0
    dif =(X[i])-(y_bar) 
    squared_difference = dif*dif 
    summation = summation + squared_difference 
MSE = summation/n 
print("The Mean Square Error is: ",MSE)

[[2012.917     32.        84.87882   10.        24.98298  121.54024]
 [2012.917     19.5      306.5947     9.        24.98034  121.53951]
 [2013.583     13.3      561.9845     5.        24.98746  121.54391]
 ...
 [2013.25      18.8      390.9696     7.        24.97923  121.53986]
 [2013.         8.1      104.8101     5.        24.96674  121.54067]
 [2013.5        6.5       90.45606    9.        24.97433  121.5431 ]]
[[  0.        0.        0.      ...  84.87882  24.98298 121.54024]
 [  0.        0.        0.      ... 306.5947   24.98034 121.53951]
 [  0.        0.        0.      ... 561.9845   24.98746 121.54391]
 ...
 [  0.        0.        0.      ... 390.9696   24.97923 121.53986]
 [  0.        0.        0.      ... 104.8101   24.96674 121.54067]
 [  0.        0.        0.      ...  90.45606  24.97433 121.5431 ]]
[[43.53 45.3 ]
 [15.51 14.4 ]
 [44.89 46.  ]
 [15.4  15.6 ]
 [46.05 50.2 ]
 [41.44 38.1 ]
 [38.41 48.5 ]
 [36.79 41.4 ]
 [47.44 51.6 ]
 [46.96 40.1 ]
 [43.65 42.  ]
 [41.35 42.4 ]
 [42.95 28.5 ]
 [37.9  39.1 ]
 [49.53 53.7 ]
 [32.95 36.8 ]
 [37.64 40.6 ]
 [43.75 55.2 ]
 [41.52 39.3 ]
 [44.65 44.3 ]
 [50.31 53.5 ]
 [31.04 25.3 ]
 [41.62 22.8 ]
 [46.63 51.7 ]
 [46.53 45.5 ]
 [40.97 34.4 ]
 [48.09 31.6 ]
 [23.27 25.9 ]
 [49.22 49.5 ]
 [18.39 24.7 ]
 [45.05 51.7 ]
 [35.37 29.7 ]
 [46.07 45.4 ]
 [34.24 50.5 ]
 [45.59 26.5 ]
 [32.3  30.1 ]
 [45.09 46.1 ]
 [35.95 28.9 ]
 [50.27 54.4 ]
 [12.23 15.  ]
 [52.81 44.9 ]
 [29.71 29.8 ]
 [30.1  23.6 ]
 [47.12 48.  ]
 [17.25 16.7 ]
 [45.46 40.9 ]
 [45.33 40.2 ]
 [14.85 12.9 ]
 [31.28 21.3 ]
 [46.6  62.1 ]
 [54.48 63.9 ]
 [37.47 40.3 ]
 [48.93 42.2 ]
 [26.55 19.1 ]
 [30.62 28.4 ]
 [30.85 28.5 ]
 [49.94 60.7 ]
 [41.69 37.5 ]
 [41.13 39.3 ]
 [33.28 28.8 ]
 [46.82 42.3 ]
 [45.98 44.3 ]
 [43.23 42.6 ]
 [44.97 57.4 ]
 [38.96 42.2 ]
 [25.69 25.7 ]
 [12.88 13.2 ]
 [31.13 27.  ]
 [47.06 56.2 ]
 [41.44 38.3 ]
 [31.11 20.8 ]
 [47.13 43.1 ]
 [45.76 78.3 ]
 [27.87 20.9 ]
 [38.15 32.5 ]
 [32.01 33.4 ]
 [26.71 32.1 ]
 [15.81 19.2 ]
 [48.31 53.  ]
 [43.42 38.2 ]
 [49.86 46.7 ]
 [29.01 24.6 ]
 [46.53 36.2 ]]
The Mean Square Error is:  [1.70e+03 1.70e+03 1.70e+03 1.70e+03 1.70e+03 1.69e+03 1.70e+03 1.70e+03
 1.70e+03 1.70e+03 1.70e+03 3.90e+06 8.32e+02 2.70e+06 3.81e+02 7.00e+03]